import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const handlers={}, opened=[];
const parent={};
const link={href:'https://example.org/next',textContent:'Next',getBoundingClientRect:()=>({left:5,bottom:10}),contains:()=>false};
const child={top:parent,parent:{postMessage:data=>opened.push(data)},addEventListener:(k,v)=>handlers[k]=v};
vm.runInNewContext(fs.readFileSync('browser-extension/content.js','utf8'),{window:child,document:{addEventListener:(k,v)=>handlers[k]=v},URL,location:{href:'https://example.org'}});
const frame={contentWindow:{postMessage:data=>handlers.message?.({isTrusted:true,source:child.parent,data})}};
const source=fs.readFileSync('vyasa/extensions_builtin/link_preview/static/link_preview.js','utf8');
const root={document:{querySelector:()=>frame},modifierDown:false,hoveredLink:null,previews:{open(){throw Error('wrong root link')}}};
vm.createContext(root);
vm.runInContext(source.slice(source.indexOf('function trackModifier('),source.indexOf('function handleKeydown(')),root);
handlers.pointerover({isTrusted:true,metaKey:false,target:{closest:()=>link}});
root.trackModifier({isTrusted:true,metaKey:true,ctrlKey:false});
assert.equal(opened.length,1,'hover first, then Cmd in parent must open preview');
root.trackModifier({isTrusted:true,metaKey:true,ctrlKey:false});assert.equal(opened.length,1);
root.trackModifier({isTrusted:true,metaKey:false,ctrlKey:false});
root.trackModifier({isTrusted:true,metaKey:false,ctrlKey:true});assert.equal(opened.length,2);
handlers.keyup({metaKey:false,ctrlKey:false});
handlers.pointerover({isTrusted:true,metaKey:true,target:{closest:()=>link}});assert.equal(opened.length,3);
handlers.pointerout({isTrusted:true,relatedTarget:null});
root.trackModifier({isTrusted:true,metaKey:true,ctrlKey:false});assert.equal(opened.length,3);
console.log('PASS: both gesture orders, Cmd/Ctrl, no repeats, release/repress, and stale hover cleanup');
