theme_primary = "#c0852f"
theme_heading_font = "\"Hepta Slab\", Georgia, serif"
theme_body_font = "Karla, sans-serif"
theme_ui_font = "Karla, sans-serif"
theme_dark_paper = "#1c140c"
theme_dark_paper_low = "#2d2011"
theme_dark_paper_raised = "#392817"
theme_dark_paper_accent = "#52381f"
theme_ink = "#412d1f"
theme_ink_soft = "#8e7860"
theme_dark_ink = "#f9efdf"
theme_dark_ink_soft = "#e0c397"
theme_selection_bg = "#c0852f"
theme_selection_fg = "#fff8ef"
