theme_primary = "#00fbfb"
theme_heading_font = "Newsreader, Georgia, serif"
theme_body_font = "Inter, sans-serif"
theme_ui_font = "\"Space Grotesk\", Inter, sans-serif"
theme_paper = "#f6ffff"
theme_paper_low = "#e7ffff"
theme_paper_raised = "#ffffff"
theme_ink = "#151515"
theme_dark_paper = "#131313"
theme_dark_paper_low = "#1c1b1b"
theme_dark_paper_raised = "#353534"
theme_dark_ink = "#f5feff"
theme_selection_bg = "#00fbfb"
