theme_primary = "#a1faff"
theme_heading_font = "\"Space Grotesk\", Inter, sans-serif"
theme_body_font = "Inter, sans-serif"
theme_ui_font = "\"IBM Plex Mono\", monospace"
theme_paper = "#f4ffff"
theme_paper_low = "#e4ffff"
theme_paper_raised = "#ffffff"
theme_ink = "#101718"
theme_dark_paper = "#0e0e0e"
theme_dark_paper_low = "#151515"
theme_dark_paper_raised = "#232323"
theme_dark_ink = "#e7ffff"
theme_selection_bg = "#a1faff"

