theme_primary = "#667446"
code_theme_light = "base16/gruvbox-light-medium"
code_theme_dark = "base16/woodland"
theme_button_radius = "0.4rem"
theme_heading_font = "Domine, Georgia, serif"
theme_body_font = "Lexend, sans-serif"
theme_ui_font = "Lexend, sans-serif"
theme_mono_font = "\"Ubuntu Mono\", monospace"
theme_dark_paper = "#151912"
theme_dark_paper_low = "#232a1c"
theme_dark_paper_raised = "#2b3422"
theme_dark_paper_accent = "#3a472f"
theme_ink = "#323726"
theme_ink_soft = "#767b66"
theme_dark_ink = "#f0f4e8"
theme_dark_ink_soft = "#c0c9af"
theme_selection_bg = "#667446"
theme_selection_fg = "#f8fbf1"
