# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/bloggy',
                'doc_host': 'https://sizhky.github.io',
                'git_url': 'https://github.com/sizhky/bloggy',
                'lib_path': 'bloggy'},
  'syms': { 'bloggy.core': { 'bloggy.core.get_posts': ('core.html#get_posts', 'bloggy/core.py'),
                             'bloggy.core.index': ('core.html#index', 'bloggy/core.py'),
                             'bloggy.core.layout': ('core.html#layout', 'bloggy/core.py'),
                             'bloggy.core.navbar': ('core.html#navbar', 'bloggy/core.py'),
                             'bloggy.core.post_detail': ('core.html#post_detail', 'bloggy/core.py'),
                             'bloggy.core.theme_toggle': ('core.html#theme_toggle', 'bloggy/core.py')},
            'bloggy.main': {}}}
