"""The core contents and layout of the blog application."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

__all__ = ['hdrs', 'app', 'rt', 'NAVBAR_CLS', 'FOOTER_CLS', 'MAIN_CLS', 'CONTAINER_CLS', 'LINK_CLS', 'TOGGLE_BTN_CLS',
           'theme_toggle', 'navbar', 'layout', 'get_posts', 'post_detail', 'index']


from fasthtml.common import *
from fasthtml.jupyter import *
from monsterui.all import *


global ROOT_FOLDER
hdrs = (
    *Theme.slate.headers(highlightjs=True),
    Link(rel="icon", href="/static/favicon.png"),
    Script(src="https://unpkg.com/hyperscript.org@0.9.12"),
    Script(src="/static/scripts.js", type='module'),
    Link(rel="preconnect", href="https://fonts.googleapis.com"), Link(rel="preconnect", href="https://fonts.gstatic.com", crossorigin=""),
    Link(rel="stylesheet", href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600;700&family=IBM+Plex+Mono&display=swap"),
    Style("body { font-family: 'IBM Plex Sans', sans-serif; } code, pre { font-family: 'IBM Plex Mono', monospace; }"),
    Style(".folder-chevron { transition: transform 0.2s; display: inline-block; } details[open] > summary > .folder-chevron { transform: rotate(90deg); }  details { border: none !important; box-shadow: none !important; }"),
    Script("if(!localStorage.__FRANKEN__) localStorage.__FRANKEN__ = JSON.stringify({mode: 'light'})"))

app = FastHTML(hdrs=hdrs)
rt = app.route


# CSS class definitions for reusable components
NAVBAR_CLS = "flex items-center justify-between bg-slate-900 text-white p-4 my-4 rounded-lg shadow-md dark:bg-slate-800"
FOOTER_CLS = "bg-slate-900 text-white rounded-lg p-4 my-4 dark:bg-slate-800"
MAIN_CLS = "w-full max-w-2xl mx-auto px-6 py-8 space-y-8"
CONTAINER_CLS = "w-full max-w-2xl mx-auto"
LINK_CLS = "text-blue-600 hover:underline py-2"
TOGGLE_BTN_CLS = "p-1 hover:scale-110 shadow-none"

def get_root_folder():
    import os
    from pathlib import Path
    return Path(os.getenv('BLOGGY_ROOT', '.')).resolve()

def theme_toggle():
    return Button(UkIcon("moon", cls="dark:hidden"), UkIcon("sun", cls="hidden dark:block"),
        _="""on load
                set franken to (localStorage's __FRANKEN__ or '{}') as Object
                if franken's mode is 'dark' then add .dark to <html/> end
                on click
                toggle .dark on <html/>
                set franken to (localStorage's __FRANKEN__ or '{}') as Object
                if the first <html/> matches .dark set franken's mode to 'dark' else set franken's mode to 'light' end
                set localStorage's __FRANKEN__ to franken as JSON""",
        cls=TOGGLE_BTN_CLS, type="button")

def navbar():
    return Div(
        A("Bloggy", href="/"),
        theme_toggle(),
        cls=NAVBAR_CLS
    )

def layout(*content, htmx, title=None):
    if htmx and htmx.request: return (Title(title), *content)
    main = Main(*content, cls=MAIN_CLS, id="main-content")
    return Title(title), Div(cls="flex flex-col min-h-screen")(
        Div(navbar(), cls=f"{CONTAINER_CLS} px-4 sticky top-0 z-50 mt-4"),
        main,
        Footer(Div("Footer Placeholder", cls=FOOTER_CLS), cls=f'{CONTAINER_CLS} px-6 mt-auto mb-6 sticky bottom-0 z-50')
    )

def build_post_tree(folder):
    """Recursively build a collapsible tree of posts and folders"""
    ROOT_FOLDER = get_root_folder()
    items = []
    
    try:
        entries = sorted(folder.iterdir(), key=lambda x: (not x.is_dir(), x.name))
    except (OSError, PermissionError):
        return items
    
    for item in entries:
        if item.is_dir():
            # Skip hidden directories
            if item.name.startswith('.'):
                continue
            sub_items = build_post_tree(item)
            if sub_items:  # Only show folder if it has content
                items.append(Li(
                    Details(
                        Summary(
                            UkIcon("chevron-right", cls="folder-chevron w-4 h-4 mr-1 text-slate-400"),
                            Span(UkIcon("folder", cls="text-blue-500"), cls="w-5 flex justify-center mr-2"),
                            item.name,
                            cls="flex items-center font-medium cursor-pointer py-1 px-2 hover:text-blue-600 select-none list-none rounded hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
                        ),
                        Ul(*sub_items, cls="ml-6 pl-2 space-y-1 border-l border-slate-100 dark:border-slate-800"),
                        open=False
                    ),
                    cls="my-1"
                ))
        elif item.suffix == '.md':
            rel_path = item.relative_to(ROOT_FOLDER).with_suffix('')
            slug = str(rel_path)
            items.append(Li(
                A(
                    Div(
                        Span(cls="w-4 mr-1"), # Spacer for chevron alignment
                        Span(UkIcon("file-text", cls="text-slate-400"), cls="w-5 flex justify-center mr-2"),
                        item.stem, 
                        cls="flex items-center"
                    ),
                    href=f'/posts/{slug}', 
                    cls=f"block py-1 px-2 rounded hover:bg-slate-100 dark:hover:bg-slate-800 text-slate-700 dark:text-slate-300 hover:text-blue-600 transition-colors"
                )
            ))
    
    return items

def get_posts(): 
    """Get posts as a collapsible tree structure"""
    ROOT_FOLDER = get_root_folder()
    return build_post_tree(ROOT_FOLDER)

@rt('/posts/{path:path}')
def post_detail(path: str, htmx):
    # path parameter already includes the full path with slashes
    ROOT_FOLDER = get_root_folder()
    file_path = ROOT_FOLDER / f'{path}.md'
    with open(file_path) as f:
        content = render_md(f)
    return layout(
        H1(f"Post: {path}", cls="text-4xl font-bold"),
        content,
        htmx=htmx,
        title=f"{path} - Bloggy",
    )

@rt
def index(htmx):
    return layout(
        Div(
            H1("Welcome to Bloggy!", cls="text-4xl font-bold tracking-tight mb-2"),
            P("Your personal blogging platform.", cls="text-lg text-slate-600 dark:text-slate-400 mb-8"),
            Card(
                Div(
                    H2("Posts", cls="text-xl font-semibold"),
                    cls="border-b border-slate-100 dark:border-slate-700 pb-4 mb-4"
                ),
                Ul(*get_posts(), cls="space-y-1"),
                cls="p-6 shadow-sm hover:shadow-md transition-shadow bg-white dark:bg-slate-900"
            ),
            cls="w-full"
        ),
        htmx=htmx,
        title="Home - Bloggy",
    )
